version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      - NODE_ENV=production
    networks:
      - my-network
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: bykea_re
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network
  redis:
    image: redis:latest
    container_name: my-redis-container
    ports:
      - "6379:6379"
    networks:
      - my-network    
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - my-network    
networks:
  my-network:
volumes:
  postgres-data:
